apiVersion: v1
kind: ConfigMap
metadata:
  name: deposit-service-config
data:
  application.yml: |
    server:
      port: 8088

    spring:
      cache:
        type: redis
        cache-names: redis-cache
      data:
        redis:
          host: redis-service
          port: 6379

      datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_PATH}
        username: postgres
        password: postgres
        hikari:
          maximum-pool-size: 10

      jpa:
        show-sql: true
        hibernate:
          ddl-auto: validate

    management:
      endpoints:
        web:
          exposure:
            include: health, info, metrics, prometheus
      metrics:
        distribution:
          percentiles-histogram:
            http:
              server:
                requests: true
        tags:
          application: ${spring.application.name}
      observations:
        key-values:
          application: ${spring.application.name}
      tracing:
        sampling:
          probability: 1.0

    crone-for-simple-calculating: "0 0 22 * * *"